# Generated by Django 3.1.7 on 2022-06-22 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '種類',
                'verbose_name_plural': '種類',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '顏色',
                'verbose_name_plural': '顏色',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '尺寸',
                'verbose_name_plural': '尺寸',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255)),
                ('unit_prize', models.PositiveIntegerField(default=0)),
                ('inventory', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='種類')),
                ('color', models.ManyToManyField(to='product.Color')),
                ('size', models.ManyToManyField(to='product.Size')),
            ],
            options={
                'verbose_name': '產品',
                'verbose_name_plural': '產品',
            },
        ),
    ]
